export {
  CARGO_READINESS_OPTIONS,
  TRANSPORT_MODE_OPTIONS,
  INCOTERM_OPTIONS,
  FREIGHT_CUSTOMER_TYPES,
  COURIER_DESTINATION_OPTIONS,
  WEIGHT_SLAB_OPTIONS,
  FREIGHT_DEAL_STAGES,
  getFreightCustomerTypeMeta,
  showsSpotRfqFields,
  showsCourierFields,
  emptyFreightRfq,
  emptyFreightBox,
  emptyCourierProfile,
  isFreightDealOrg,
  getFreightDealStageMeta,
} from '../../../lib/freightDeal.js'
