/** Demo leads shown before Claude AI search is connected */
export const MOCK_LEADS = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Chen',
    title: 'VP of Marketing',
    company: 'TechFlow SaaS',
    companyDomain: 'techflow.io',
    email: 'sarah.chen@techflow.io',
    phone: '+1 (415) 555-0142',
    location: 'San Francisco, CA',
    industry: 'Software',
    employees: '51-200',
    linkedin: 'linkedin.com/in/sarahchen',
    emailStatus: 'verified',
    score: 92,
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Webb',
    title: 'Head of Growth',
    company: 'ScaleUp Labs',
    companyDomain: 'scaleuplabs.com',
    email: 'marcus@scaleuplabs.com',
    phone: '+1 (212) 555-0198',
    location: 'New York, NY',
    industry: 'Marketing & Advertising',
    employees: '11-50',
    linkedin: 'linkedin.com/in/marcuswebb',
    emailStatus: 'verified',
    score: 88,
  },
  {
    id: '3',
    firstName: 'Priya',
    lastName: 'Sharma',
    title: 'Director of Sales',
    company: 'CloudNine Systems',
    companyDomain: 'cloudnine.io',
    email: 'priya.sharma@cloudnine.io',
    phone: '+1 (512) 555-0167',
    location: 'Austin, TX',
    industry: 'Information Technology',
    employees: '201-500',
    linkedin: 'linkedin.com/in/priyasharma',
    emailStatus: 'likely',
    score: 85,
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Okonkwo',
    title: 'CMO',
    company: 'BrightPath Health',
    companyDomain: 'brightpathhealth.com',
    email: 'j.okonkwo@brightpathhealth.com',
    phone: '+1 (617) 555-0134',
    location: 'Boston, MA',
    industry: 'Healthcare',
    employees: '501-1000',
    linkedin: 'linkedin.com/in/jamesokonkwo',
    emailStatus: 'verified',
    score: 79,
  },
  {
    id: '5',
    firstName: 'Elena',
    lastName: 'Rodriguez',
    title: 'Marketing Manager',
    company: 'GreenLeaf Commerce',
    companyDomain: 'greenleaf.co',
    email: 'elena@greenleaf.co',
    phone: '+1 (305) 555-0189',
    location: 'Miami, FL',
    industry: 'E-commerce',
    employees: '11-50',
    linkedin: 'linkedin.com/in/elenarodriguez',
    emailStatus: 'verified',
    score: 76,
  },
  {
    id: '6',
    firstName: 'David',
    lastName: 'Kim',
    title: 'Founder & CEO',
    company: 'NexGen Analytics',
    companyDomain: 'nexgenanalytics.ai',
    email: 'david@nexgenanalytics.ai',
    phone: '+1 (206) 555-0156',
    location: 'Seattle, WA',
    industry: 'Data & Analytics',
    employees: '1-10',
    linkedin: 'linkedin.com/in/davidkim',
    emailStatus: 'likely',
    score: 94,
  },
  {
    id: '7',
    firstName: 'Amanda',
    lastName: 'Foster',
    title: 'VP Sales',
    company: 'RetailMax Pro',
    companyDomain: 'retailmaxpro.com',
    email: 'afoster@retailmaxpro.com',
    phone: '+1 (312) 555-0171',
    location: 'Chicago, IL',
    industry: 'Retail',
    employees: '201-500',
    linkedin: 'linkedin.com/in/amandafoster',
    emailStatus: 'verified',
    score: 81,
  },
  {
    id: '8',
    firstName: 'Tom',
    lastName: 'Harrison',
    title: 'Business Development Lead',
    company: 'FinEdge Capital',
    companyDomain: 'finedge.capital',
    email: 'tom.harrison@finedge.capital',
    phone: '+1 (646) 555-0123',
    location: 'New York, NY',
    industry: 'Financial Services',
    employees: '51-200',
    linkedin: 'linkedin.com/in/tomharrison',
    emailStatus: 'unverified',
    score: 72,
  },
]
