/** Indian B2B sample leads — offline fallback for Connect Intel search */

export const MOCK_LEADS = [
  {
    id: '1',
    firstName: 'Rahul',
    lastName: 'Mehta',
    title: 'Export Manager',
    company: 'Jaipur Textile Exports Pvt Ltd',
    companyDomain: 'jaipurtextile.com',
    email: 'rahul.mehta@jaipurtextile.com',
    phone: '+91-141-2551234',
    location: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    city: 'Jaipur',
    industry: 'Textiles & Garments',
    employees: '51-200',
    linkedin: 'linkedin.com/in/rahulmehta',
    emailStatus: 'verified',
    score: 91,
    source: 'database',
  },
  {
    id: '2',
    firstName: 'Priya',
    lastName: 'Sharma',
    title: 'CEO / Founder',
    company: 'SpiceRoute Organics',
    companyDomain: 'spiceroute.in',
    email: 'priya@spiceroute.in',
    phone: '+91-22-40001234',
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    city: 'Mumbai',
    industry: 'Agri & Food Export',
    employees: '11-50',
    emailStatus: 'verified',
    score: 88,
    source: 'database',
  },
  {
    id: '3',
    firstName: 'Arjun',
    lastName: 'Reddy',
    title: 'VP Sales',
    company: 'Hyderabad Pharma Labs',
    companyDomain: 'hydpharma.com',
    email: 'arjun.reddy@hydpharma.com',
    phone: '+91-40-44556677',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    city: 'Hyderabad',
    industry: 'Pharmaceuticals',
    employees: '201-500',
    emailStatus: 'likely',
    score: 85,
    source: 'database',
  },
  {
    id: '4',
    firstName: 'Anita',
    lastName: 'Desai',
    title: 'Head of Marketing',
    company: 'Surat Diamond Crafts',
    companyDomain: 'suratdiamond.co',
    email: 'anita@suratdiamond.co',
    phone: '+91-261-2345678',
    location: 'Surat, Gujarat',
    state: 'Gujarat',
    city: 'Surat',
    industry: 'Gems & Jewellery',
    employees: '51-200',
    emailStatus: 'verified',
    score: 82,
    source: 'database',
  },
  {
    id: '5',
    firstName: 'Vikram',
    lastName: 'Singh',
    title: 'Business Development',
    company: 'Noida IT Solutions',
    companyDomain: 'noidaits.in',
    email: 'vikram.singh@noidaits.in',
    phone: '+91-120-4567890',
    location: 'Delhi NCR',
    state: 'Delhi NCR',
    city: 'Delhi',
    industry: 'IT & Software',
    employees: '51-200',
    emailStatus: 'verified',
    score: 79,
    source: 'database',
  },
  {
    id: '6',
    firstName: 'Kavita',
    lastName: 'Iyer',
    title: 'Director Operations',
    company: 'Coimbatore Engineering Works',
    companyDomain: 'coimbatoreeng.com',
    email: 'kavita.iyer@coimbatoreeng.com',
    phone: '+91-422-3012345',
    location: 'Coimbatore, Tamil Nadu',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    industry: 'Engineering & Manufacturing',
    employees: '201-500',
    emailStatus: 'likely',
    score: 76,
    source: 'database',
  },
  {
    id: '7',
    firstName: 'Mohammed',
    lastName: 'Khan',
    title: 'Export Manager',
    company: 'Kochi Marine Foods',
    companyDomain: 'kochimarine.in',
    email: 'mkhan@kochimarine.in',
    phone: '+91-484-2701234',
    location: 'Kochi, Kerala',
    state: 'Kerala',
    city: 'Kochi',
    industry: 'Agri & Food Export',
    employees: '11-50',
    emailStatus: 'verified',
    score: 84,
    source: 'database',
  },
  {
    id: '8',
    firstName: 'Sneha',
    lastName: 'Patil',
    title: 'Marketing Manager',
    company: 'Pune Auto Components Ltd',
    companyDomain: 'puneauto.com',
    email: 'sneha.patil@puneauto.com',
    phone: '+91-20-25678901',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    city: 'Pune',
    industry: 'Automotive Components',
    employees: '501-1000',
    emailStatus: 'verified',
    score: 80,
    source: 'database',
  },
]
